# conda env create -f environment.yml
# conda remove --name my-rhino-env --all

name: my-rhino-env
channels:
  - pytorch
  - conda-forge
  - defaults

variables:
  KMP_DUPLICATE_LIB_OK: "TRUE"
  OMP_NUM_THREADS: "1"

dependencies:
  - python=3.10
  - pip
  - rdkit
  - pytorch
  - torchvision
  - torchaudio
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - pytorch-lightning
  - joblib
  - tqdm
  - pip:
      - PyTDC
      - chemprop
      - tensorboard
